In [17]:
import pandas as pd
df = pd.read_csv("diabetes_prediction_dataset.csv")
df.head()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [19]:
df.drop_duplicates(inplace=True)
df.dropna()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99994,Female,36.0,0,0,No Info,24.60,4.8,145,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [21]:
df['gender'] = df['gender'].astype('float32')
df['smoking_history'] = df['smoking_history'].astype('category')
df['hypertension'] = df['hypertension'].astype('int8')
df['heart_disease'] = df['heart_disease'].astype('int8')
df['diabetes'] = df['diabetes'].astype('int8')
df['age'] = df['age'].astype('float32')
df['bmi'] = df['bmi'].astype('float32')
df['HbA1c_level'] = df['HbA1c_level'].astype('float32')
df['blood_glucose_level'] = df['blood_glucose_level'].astype('float32')

ValueError: could not convert string to float: 'Female'

In [ ]:
def count_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return ((data[column] < lower) | (data[column] > upper)).sum()

In [ ]:
for col in ['age', 'bmi', 'HbA1c_level', 'blood_glucose_level']:
    print(f'{col}: {count_outliers_iqr(df, col)} outliers')

df.to_csv('diabetes_prediction_dataset_cleaned.csv', index=False)

print('Cleaning complete. Cleaned file saved.')

In [22]:
gender_mapping = {'Female': 0, 'Male': 1, 'Other': 2}
df['gender'] = df['gender'].map(gender_mapping)

smoking_mapping = {
    'never': 0,
    'current': 1,
    'former': 2,
    'ever': 3,
    'not current': 4
}
df['smoking_history'] = df['smoking_history'].map(smoking_mapping).fillna(-1).astype('int8')

In [23]:
df.to_csv('diabetes_prediction_dataset_cleaned.csv', index=False)